language: scala
scala:
  - 2.11.8

jdk:
  - oraclejdk8
  - oraclejdk7

before_script:
  - wget https://github.com/Ichoran/thyme/raw/master/Thyme.jar -O /tmp/Thyme.jar
  - mkdir lib
  - cp /tmp/Thyme.jar lib
  - apt-get -yyq update
  - apt-cache showpkg docker-engine
  - service docker stop
  - apt-get -yyq rm docker-engine
  - apt-get -yyq install docker-engine=1.11.2-0~xenial
  - service docker start
  - service docker run hello-world
script:
  - sbt clean
  - sbt "testOnly com.weather.scalacass.CaseClassUnitTests"
  - sbt "testOnly com.weather.scalacass.CreateTableUnitTests"
  - sbt "testOnly com.weather.scalacass.ScalaCassUnitTestsAll"
  - sbt "testOnly com.weather.scalacass.SessionActionsUnitTest"

sudo: required

services:
  - docker

env:
  - DOCKER_HOST=unix:///var/run/docker.sock

addons:
  hosts:
    - dockerhost
