language: scala
scala:
  - 2.11.8

jdk:
  - oraclejdk7

before_script:
  - wget https://github.com/Ichoran/thyme/raw/master/Thyme.jar -O /tmp/Thyme.jar
  - mkdir lib
  - cp /tmp/Thyme.jar lib
script: sbt +test

sudo: required

services:
  - docker

env:
  - DOCKER_HOST=unix:///var/run/docker.sock

addons:
  hosts:
    - dockerhost
