# use containers
sudo: false

dist: trusty

language: scala

scala:
  - 2.11.12

jdk:
  - oraclejdk8

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_script: 
  - mkdir lib
  - wget https://github.com/Ichoran/thyme/raw/master/Thyme.jar -O lib/Thyme.jar

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b37d78d8e7cb1d34adb3
