language: scala
scala:
  - 2.11.8

jdk:
  - oraclejdk7

before_script:
  - wget https://github.com/Ichoran/thyme/raw/master/Thyme.jar -O /tmp/Thyme.jar
  - echo $DOCKER_HOST
script:
  - mkdir lib
  - cp /tmp/Thyme.jar lib
  - sbt +test
sudo: required

services:
  - docker
